# Overrides the snippet from Debian's nix-setup-systemd. The per-user profile
# and gcroots directories are created by the daemon itself on first use
# (Nix >= 2.14 keeps their parents root-owned), so only the home links stay.
#Type Path        Mode UID  GID  Age Argument
d     %h/.nix-defexpr
L     %h/.nix-defexpr/channels_root -    -    -    -  /nix/var/nix/profiles/per-user/root/channels
L     %h/.nix-profile -    -    -    -  /nix/var/nix/profiles/per-user/%u/profile
